### ISSUE TITLE
[GALAGUERRE] Carte Professeur Damien

### ISSUE THREAD

**Issue by ThomasGaladrim** [mle-moni/galadrim-tools#133]
Regardez votre deck et choisissez 5 cartes que vous mettez de côté.
Mélanger votre deck puis remettez les 5 cartes dans l'ordre souhaite au-dessus de votre deck

#Galaguerre 😎

**Comment by mle-moni** [comment]
un peu complexe comme fonctionnement je trouve, au debut on va rester le plus simple possible x)

on va implementer un systeme de découverte comme dans HS, donc peut etre qu'on peut utiliser une découverte pour cette carte ? genre l'effet de la carte serait "découvre une carte TECHNOLOGIE"

TECHNOLOGIE serait un tag de carte, on pourrait imaginer des cartes NODEJS, PHP et autres 😛
