### ISSUE TITLE
Fichier README n'est plus à jour

### ISSUE THREAD

**Issue by DDeredec** [mle-moni/galadrim-tools#48]
## Problème actuel

Le [fichier README](https://github.com/mle-moni/galadrim-tools/blob/master/README.md) de ce repo n'est plus d'actualité, il correspond à l'ancienne version qui ne comportait que l'onglet Rooms.

## Solution attendue

Il faudrait que le contenu du README matchent les derniers changements effectués et listent l'intégralité des outils proposés aujourd'hui, avec une brève description.

## Screenshot

![image](https://user-images.githubusercontent.com/33863581/186181058-9c937c7e-2c1d-46ff-9eb9-5d146f4ea71b.png)

**Comment by mle-moni** [comment]
solved in #55
