### ISSUE TITLE
Ajouter une page "Nouveautés" pour l'onglet "saveur"

### ISSUE THREAD

**Issue by DDeredec** [mle-moni/galadrim-tools#50]
## Situation actuelle

Aujourd'hui, l'onglet `/saveur` comporte une page de statistiques, mais qui recense 5 restaurants avec beaucoup de votes. L'ajout de nouveaux restaurants par d'autres utilisateurs n'est pas favorisé car on ne peut pas savoir facilement ce qui a été ajouté.

## Solution proposée

Ajouter une nouvelle page à l'onglet `/saveur`, qui afficherait les X derniers restaurants ajoutés par les utilisateurs (quantité à déterminer).

**Comment by mle-moni** [comment]
Sinon c'est une bonne idée :smile:

**Comment by DDeredec** [comment]
> montre les 5 restaurants avec le meilleur score

je suis d'accord, mais jusqu'à maintenant, les meilleurs scores observés étaientt occupé par des restaurants régulièrement visité, qui faisaient de l'ombre sur les nouveaux restaurants ajoutés 😉
