### ISSUE TITLE
ajouter phone box

### ISSUE THREAD

**Issue by mle-moni** [mle-moni/galadrim-tools#60]
La nouvelle phone box vient d'arriver.
Il faudrait pouvoir reserver celle-ci comme on ferait pour une salle classique

**Comment by mle-moni** [comment]
@matthieu-locussol 
Je sais pas trop si il vaut mieux mettre a jour le SVG que tu avais fait ou alors commencer un systeme different
(par exemple un systeme ou un admin peut ajouter des salles sans avoir a coder :fearful:)
Tu as un avis sur la question ?

**Comment by matthieu-locussol** [comment]
> @matthieu-locussol Je sais pas trop si il vaut mieux mettre a jour le SVG que tu avais fait ou alors commencer un systeme different (par exemple un systeme ou un admin peut ajouter des salles sans avoir a coder 😨) Tu as un avis sur la question ?

Je n'ai pas d'idée de système no-code permettant d'obtenir un rendu SVG aussi "propre" que ce que l'on a actuellement.
Le plus simple selon moi serait de mettre à jour le plan existant sur Figma, ré-exporter le SVG et le re-wrapper dans un component React.

Il y a un nouveau plan ?

**Comment by mle-moni** [comment]
closed by #63
