### ISSUE TITLE
Pouvoir partager un lien pour chaque restaurant

### ISSUE THREAD

**Issue by DDeredec** [mle-moni/galadrim-tools#66]
## Proposition

Aujourd'hui, il n'est pas possible de partager un lien d'un restaurant sur _Galamiam_.

Le but serait de pouvoir obtenir un lien de partage lorsqu'on a cliqué sur un restaurant existant.
Par exemple, on pourrait avoir un query param pour pointer vers un des restaurants.

**Comment by mle-moni** [comment]
closed by #75
