### ISSUE TITLE
Impossible de rouvrir un restaurant quand on l'a fermé

### ISSUE THREAD

**Issue by Reloadaxe** [mle-moni/galadrim-tools#80]
Quand on clique sur un restaurant, puis qu'on clique sur la croix dans la modal (celle qui contient l'image), et enfin qu'on reclique sur le restaurant sur la carte, la modal ne s'ouvre plus tant qu'on ne clique pas sur un autre restaurant

**Comment by mle-moni** [comment]
closed by #101
